name: Cypress CI

on:
  pull_request:
    branches:
      - master

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npx http-server -p 3000 &
      

      - name: Run Cypress and save output
        run: |
          set -o pipefail
          echo '## Test Report' > test_report.md
          echo '```' >> test_report.md
          npx cypress run --project ./test \
          --spec test/cypress/e2e/test_suite.cy.js \
          --browser firefox | sed 's/\x1b\[[0-9;]*m//g' >> test_report.md
          echo '```' >> test_report.md

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: test_report.md

      # - name: Run Test
      #   uses: cypress-io/github-action@v6
      #   with:
      #     project: ./test
      #     spec: test/cypress/e2e/test_suite.cy.js
      #     wait-on: 'http://localhost:3000'
      #     browser: firefox    
      
      # - name: Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots
      #     if-no-files-found: ignore

      # - name: Upload Artifact     
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
      #     if-no-files-found: ignore
